---
title: "Lab 4"
author: "Janice Chong See Wai"
date: '2022-04-07'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# **Resubmitted after some corrections

## Function myCGPA that calculate students' CGPA
```{r}
myGPA <- function(marks, creditHrs){
  gp <- 0
  for(i in 1:length(marks)){
    if(marks[i] >=80){
      gp <- gp + (4*creditHrs[i]) 
    }
    else if(marks[i] >=75){
      gp <- gp + (3.7*creditHrs[i])
    }
    else if(marks[i] >= 70){
      gp <- gp + (3.3*creditHrs[i])
    }
    else if(marks[i] >= 65){
      gp <- gp + (3*creditHrs[i])
    }
    else if(marks[i] >= 60){
      gp <- gp + (2.7*creditHrs[i])
    }
    else if(marks[i] >= 55){
      gp <- gp + (2.3*creditHrs[i])
    }
    else if(marks[i] >= 50){
      gp <- gp + (2*creditHrs[i])
    }
    else if(marks[i] >= 45){
      gp <- gp + (1.7*creditHrs[i])
    }
    else if(marks[i] >= 40){
      gp <- gp + (1.3*creditHrs[i])
    }
    else if(marks[i] >= 35){
      gp <- gp + (1*creditHrs[i])
    }
    else{
      gp <- gp + 0
    }
  }
  GPA <- gp / sum(creditHrs)
  return(GPA)
}

myCGPA <- function(GPA, creditHrs){
  total <- 0
  for (i in range(2)) {
    total <- total + (sum(creditHrs[i])*GPA[i])  
  }
  CGPA <- total/sum(creditHrs)
  return(CGPA)
}

creditHrs1 <- c(4, 2, 3, 2, 1)
marks1 <- c(90, 80, 75, 99, 85)
GPA1 <- myGPA(marks1, creditHrs1)

creditHrs2 <- c(4, 2, 3, 2, 2)
marks2 <- c(80, 80, 65, 99, 65)
GPA2 <- myGPA(marks2, creditHrs2)

combineGPA <- c(GPA1, GPA2)
paste("combineGPA vector will contains : ", 
      format(round(combineGPA[1], 2), 
                   nsmall = 2),
      format(round(combineGPA[2], 2), 
                   nsmall = 2))

combineHrs <- c(sum(creditHrs1), sum(creditHrs2))
paste("combineHrs vector will contains : ",      
      combineHrs[1], combineHrs[2])

paste("CGPA : ", 
      sprintf(myCGPA(combineGPA, combineHrs), 
              fmt = "%.2f"))

```


